services:
  server:
    build: .
    container_name: http-file-server
    ports:
      - "8080:8080"
    volumes:
      - ./content:/app/content
    command: python server.py /app/content
    networks:
      - pdf-network
    restart: unless-stopped

networks:
  pdf-network:
    driver: bridge